In [1]:
import numpy as np

In [2]:
import numpy as np

# 1D Array
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)

# 2D Array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2)

[10 20 30 40 50]
[[1 2 3]
 [4 5 6]]


In [4]:
# Array Properties

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64


In [5]:
# Mathematical Operations

import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [6]:
# Scalar Operations

import numpy as np

arr = np.array([2, 4, 6, 8])

print(arr + 5)
print(arr - 2)
print(arr * 3)
print(arr / 2)

[ 7  9 11 13]
[0 2 4 6]
[ 6 12 18 24]
[1. 2. 3. 4.]


In [7]:
# Aggregate Functions

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(arr))
print("Average:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Standard Deviation:", np.std(arr))

Sum: 150
Average: 30.0
Maximum: 50
Minimum: 10
Standard Deviation: 14.142135623730951


In [8]:
# Array reshaping

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


In [9]:
# Array indexing and Slicing

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[1:4])

10
30
[20 30 40]


In [10]:
# Practice Questions
# SUM and Average

import numpy as np

arr = np.array([5, 10, 15, 20, 25])

print("Sum =", np.sum(arr))
print("Average =", np.mean(arr))

Sum = 75
Average = 15.0


In [11]:
# Square Every Element

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr ** 2)

[ 1  4  9 16 25]


In [12]:
# Find Maximum and Minimum

import numpy as np

arr = np.array([12, 45, 23, 67, 89, 10])

print("Maximum =", np.max(arr))
print("Minimum =", np.min(arr))

Maximum = 89
Minimum = 10


In [13]:
# Add Two Arrays

import numpy as np

a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print(a + b)

[ 3  7 11]


In [14]:
# Multiply Two Arrays

import numpy as np

a = np.array([2, 4, 6])
b = np.array([3, 5, 7])

print(a * b)

[ 6 20 42]
